// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgARXAJL9zj3hDYiSpe-sXk9Ky4C38liE',
    appId: '1:589582425542:web:e14de3db6263f702f1e6c7',
    messagingSenderId: '589582425542',
    projectId: 'finanzapp-e6ab6',
    authDomain: 'finanzapp-e6ab6.firebaseapp.com',
    storageBucket: 'finanzapp-e6ab6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7jc-DyEMU3rVEw5cgfNc-9Lz9kamdlw',
    appId: '1:589582425542:android:ca4f3d46184726e2f1e6c7',
    messagingSenderId: '589582425542',
    projectId: 'finanzapp-e6ab6',
    storageBucket: 'finanzapp-e6ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmTwISPNIftxFJc3zjCoVe4XZBcpELAMo',
    appId: '1:589582425542:ios:def25f12995b8a37f1e6c7',
    messagingSenderId: '589582425542',
    projectId: 'finanzapp-e6ab6',
    storageBucket: 'finanzapp-e6ab6.firebasestorage.app',
    iosBundleId: 'com.example.finanzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmTwISPNIftxFJc3zjCoVe4XZBcpELAMo',
    appId: '1:589582425542:ios:def25f12995b8a37f1e6c7',
    messagingSenderId: '589582425542',
    projectId: 'finanzapp-e6ab6',
    storageBucket: 'finanzapp-e6ab6.firebasestorage.app',
    iosBundleId: 'com.example.finanzapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgARXAJL9zj3hDYiSpe-sXk9Ky4C38liE',
    appId: '1:589582425542:web:d4b0c8bc1793ce37f1e6c7',
    messagingSenderId: '589582425542',
    projectId: 'finanzapp-e6ab6',
    authDomain: 'finanzapp-e6ab6.firebaseapp.com',
    storageBucket: 'finanzapp-e6ab6.firebasestorage.app',
  );
}
