name: Build FinanzApp
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      # Tu paso anterior que ya funcionó
      - name: Crear archivo .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # --- PASO NUEVO: Inyectar google-services.json ---
      - name: Crear google-services.json
        run: |
          cat <<EOF > android/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF
      # -------------------------------------------------
      
      - run: flutter build apk --debug