name: Build FinanzApp
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      # --- INYECTAR VARIABLES DE ENTORNO ---
      - name: Crear archivo .env
        run: echo "${{ secrets.ENV_FILE }}" > .env
      
      - run: flutter build apk --debug